apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  allow-snippet-annotations: "false"
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['localhost:9100']

      - job_name: 'pushgateway'
        static_configs:
          - targets: ['prometheus-prometheus-pushgateway.monitoramento.svc:9091']

    remote_write:
      - url: "http://10.245.115.70:80/api/v1/write"
        queue_config:
          batch_send_deadline: 5s
          max_shards: 200
          capacity: 2500
  recording_rules.yml: |
    {}
  rules: |
    {}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n  scrape_timeout: 10s\n\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n\n  - job_name: 'node-exporter'\n    static_configs:\n      - targets: ['localhost:9100']\n\n  - job_name: 'pushgateway'\n    static_configs:\n      - targets: ['prometheus-prometheus-pushgateway.monitoramento.svc:9091']\n\nremote_write:\n  - url: \"http://10.245.115.70:80/api/v1/write\"\n    queue_config:\n      batch_send_deadline: 5s\n      max_shards: 200\n      capacity: 2500\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-server","namespace":"monitoramento"}}
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoramento
  creationTimestamp: "2024-09-11T19:12:10Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.54.1
    helm.sh/chart: prometheus-25.27.0
  name: prometheus-server
  namespace: monitoramento
  resourceVersion: "4299015"
  uid: 37ae42ef-51fa-42a6-a4ea-b41ab2230caa
