apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: monitoramento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--web.listen-address=:9090"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=7d" # Armazenar dados por 7 dias
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: data-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-server
        - name: data-volume
          emptyDir: {} # Para dados temporários, você pode ajustar conforme necessário

