apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoramento
  name: prometheus-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-role-binding
  namespace: monitoramento
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoramento
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io

