apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: coturn-scaledobject
  namespace: hcce
spec:
  scaleTargetRef:
    name: coturn
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 120
  pollingInterval: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoramento.svc.cluster.local
      metricName: coturn_network_bytes_total
      query: |
        sum(rate(container_network_transmit_bytes_total{namespace="hcce", pod=~"coturn-.*"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace="hcce", pod=~"coturn-.*"}[5m]))
      threshold: "2600000" 
