apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spoke-scaledobject
  namespace: hcce
spec:
  scaleTargetRef:
    name: spoke
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 120
  pollingInterval: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoramento.svc.cluster.local
      metricName: coturn_network_bytes_total
      query: |
        sum(rate(container_network_transmit_bytes_total{namespace="hcce", pod=~"coturn-.*"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace="hcce", pod=~"coturn-.*"}[5m]))
      threshold: "666" 
      
    # Gatilho de Requisições por Segundo
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoramento.svc.cluster.local
      metricName: rate_k6_http_reqs_total
      query: rate(k6_http_reqs_total[1m])
      threshold: "135" 


